import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-stone-300 w-screen h-screen grid lg:grid-cols-2 lg:grid-rows-1 ">
        <div className="col-span-1 flex flex-col items-center justify-center h-full w-full p-20 bg-stone-500">
          <div className="flex flex-col items-center justify-center gap-6 bg-sky-200 p-10 rounded-md">  
              <p className="lg:text-2xl "> Sign in to enjoy the full features of Zest.</p>
              <Link href="/register" className="text-xl bg-stone-100 hover:bg-white transition-all shadow-md px-10 py-2 rounded-md">New User</Link>
              <Link href="/login" className="text-xl bg-stone-100 hover:bg-white transition-all shadow-md px-10 py-2 rounded-md">Log In</Link>
         </div>
        </div>
        <div className="flex flex-col col-span-1 bg-sky-200 h-full w-full items-center justify-center">
          <p className="text-5xl">Zest.</p>
          <p> Your number one source for Rust news.</p>
          </div>
      </main>
    </>
  )
}
