import Head from 'next/head'

type props = {
  children: React.ReactNode[]
}

export default function GuestLayout({children}: props) {
return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<main className="bg-stone-300 w-screen h-screen grid lg:grid-cols-2 lg:grid-rows-1 ">
        <div className="col-span-1 flex flex-col items-center justify-center h-full w-full p-20 bg-stone-500">
          <div className="flex flex-col items-center justify-center gap-10 bg-sky-200 p-10 rounded-md">  
            {children}
               </div>
        </div>
        <div className="flex flex-col col-span-1 bg-sky-200 h-full w-full items-center justify-center">
          <p className="text-7xl">Zest.</p>
          <p> Your number one app for storing notes and messages.</p>
          </div>
      </main>

  </>
)
}

